# fly.toml app configuration file generated for youtube-clone-v1 on 2023-06-09T16:31:39+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "youtube-clone-v1"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
